// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

// LoginUser provides a mock function with given fields: res, req
func (_m *AuthHandler) LoginUser(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// LogoutUser provides a mock function with given fields: res, req
func (_m *AuthHandler) LogoutUser(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

// RegisterUser provides a mock function with given fields: res, req
func (_m *AuthHandler) RegisterUser(res http.ResponseWriter, req *http.Request) {
	_m.Called(res, req)
}

type mockConstructorTestingTNewAuthHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthHandler creates a new instance of AuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthHandler(t mockConstructorTestingTNewAuthHandler) *AuthHandler {
	mock := &AuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
