// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CategoryUseCase is an autogenerated mock type for the CategoryUseCase type
type CategoryUseCase struct {
	mock.Mock
}

type mockConstructorTestingTNewCategoryUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewCategoryUseCase creates a new instance of CategoryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCategoryUseCase(t mockConstructorTestingTNewCategoryUseCase) *CategoryUseCase {
	mock := &CategoryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
