// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CatetgoryController is an autogenerated mock type for the CatetgoryController type
type CatetgoryController struct {
	mock.Mock
}

type mockConstructorTestingTNewCatetgoryController interface {
	mock.TestingT
	Cleanup(func())
}

// NewCatetgoryController creates a new instance of CatetgoryController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCatetgoryController(t mockConstructorTestingTNewCatetgoryController) *CatetgoryController {
	mock := &CatetgoryController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
